### ISSUE TITLE
Possible unintended access could be granted?

### ISSUE THREAD

**Issue by garygrubb** [imduchy/iam-minify#1]
Hi Jakub,

Thank you for this interesting project.
I have a question regarding the S3 example provided in the Readme.md

Once the minification is done, the use of the wildcard, results in an allow to unintended actions such as S3:ListBucketInventoryConfiguratioms and several others. 

Is there a way to prevent this unintended Allow/Deny?
One thing I can think of is to call AWS APIs before every minification to make sure it is safe to use a wildcard.

**Comment by imduchy** [comment]
Hello @garygrubb, thanks for reaching out.

I checked the official service reference API from AWS [1] and `s3:ListBucketInventoryConfigurations` action doesn't exist. You're probably referring to the `list-bucket-inventory-configurations` operation [2]. If you look at the CLI documentation of the action [2], it says:

> To use this operation, you must have permissions to perform the s3:GetInventoryConfiguration action.

Operations don't always have a corresponding action with the same name, just like in this example.

Hope it makes sense, and let me know if you have any other concerns or feedback.

[1] https://servicereference.us-east-1.amazonaws.com/v1/s3/s3.json
[2] https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/list-bucket-inventory-configurations.html

**Comment by garygrubb** [comment]
Thanks for the reply, @imduchy.

I was referring to an incorrect list of actions. The service reference URL you provided cleared my query.

I tested it again and the tool correctly minified "s3:ListStorageLensConfigurations" to "s3:ListStorageLensC*". This correctly avoided inclusion of "s3:ListStorageLensGroups". Thanks a lot for your explanation.

In an unrelated topic there is a missing ',' after "s3:ListMultiRegionAccessPoints" in README.md and an extra ',' in the next line.

Thanks once again for a great library and taking the time to reply.
